# GET http://localhost:4000/api/tickets?status=closed HTTP/1.1

# GET http://localhost:4000/api/tickets?priority=high HTTP/1.1

#GET http://localhost:4000/api/tickets?status=closed&priority=high HTTP/1.1

# GET http://localhost:4000/api/tickets?status=open&pageSize=5&page=3 HTTP/1.1

 GET http://localhost:4000/api/tickets?search=mijo HTTP/1.1